channel_sources:
  - conda-forge/label/m2w64-experimental,conda-forge  # [win]
  # This is for strace on linux for the a test in the full testsuite
  - conda-forge,defaults  # [linux]
# m2w64_c_compiler:
#   - gcc
# m2w64_c_compiler_version:
#   - '13'
# m2w64_c_stdlib:
#   - m2w64-sysroot
# m2w64_c_stdlib_version:
#   - '12'
# m2w64_cxx_compiler:
#   - gxx
# m2w64_cxx_compiler_version:
#   - '13'
