channel_sources:
  - conda-forge/label/m2w64-experimental,conda-forge  # [win and arm64]
  # This is for strace on linux for the a test in the full testsuite
  - conda-forge,defaults  # [linux]
m2w64_c_compiler:            # [win and x86_64]
  - gcc                      # [win and x86_64]
m2w64_c_compiler_version:    # [win and x86_64]
  - '13'                     # [win and x86_64]
m2w64_c_stdlib:              # [win and x86_64]
  - m2w64-sysroot            # [win and x86_64]
m2w64_c_stdlib_version:      # [win and x86_64]
  - '12'                     # [win and x86_64]
m2w64_cxx_compiler:          # [win and x86_64]
  - gxx                      # [win and x86_64]
m2w64_cxx_compiler_version:  # [win and x86_64]
  - '13'                     # [win and x86_64]
